# Generated by Django 3.2 on 2022-04-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates_keeper', '0002_alter_address_update_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='update_ts',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='изменён в'),
        ),
    ]
