# Generated by Django 3.2 on 2022-05-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates_keeper', '0003_alter_address_update_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='address',
            name='long',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
    ]
