# Generated by Django 3.2 on 2021-10-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20210915_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_new_order',
            field=models.BooleanField(default=True, verbose_name='Новый заказ'),
        ),
    ]
