# Generated by Django 3.2 on 2021-10-26 13:50

from django.db import migrations, models


def update_total(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    order_items = OrderItem.objects.all().annotate(
        calculated_price=models.Sum(
            models.F('product__price') * models.F('quantity')
        ))
    for oi in order_items:
        oi.total = oi.calculated_price
        oi.save()


class Migration(migrations.Migration):
    dependencies = [
        ('foodcartapp', '0043_orderitem_total'),
    ]

    operations = [
        migrations.RunPython(update_total),
    ]
