# Generated by Django 3.2 on 2021-10-27 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20211026_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена в заказе'),
            preserve_default=False,
        ),
    ]
