# Generated by Django 3.2 on 2021-10-27 06:15

from django.db import migrations, models


def update_total(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    for oi in OrderItem.objects.all():
        oi.item_price = oi.product.price
        oi.save()


class Migration(migrations.Migration):
    dependencies = [
        ('foodcartapp', '0045_auto_20211027_0612'),
    ]

    operations = [
        migrations.RunPython(update_total),
    ]
