# Generated by Django 3.2 on 2021-11-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20211027_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_new_order',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Ne', 'Новый заказ'), ('Pr', 'Обработанный'), ('Fi', 'Завершенный')], default='Ne', max_length=2),
        ),
    ]
